language: cpp
compiler:
    - gcc
    - clang
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfftw3-dev libboost-all-dev
script: ./waf configure --link-static build
